name: Build and Release TIRE App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Extract Version
        id: extract_version
        run: |
          $packageJson = Get-Content -Raw -Path "package.json" | ConvertFrom-Json
          $version = $packageJson.version
          echo "version=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Electron app
        run: npm run build

      - name: Create Release
        if: matrix.os == 'windows-latest'
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: Dr Migrate TIRE App v${{ env.version }}
          tag_name: v${{ env.version }}

      - name: Upload Windows Build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Dr Migrate TIRE App ${{ env.version }}.exe
          asset_name: Dr Migrate TIRE App ${{ env.version }}.exe
          asset_content_type: application/octet-stream

      - name: Upload Mac Build
        if: matrix.os == 'macos-latest' && steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Dr Migrate TIRE App-${{ env.version }}-mac.zip
          asset_name: Dr Migrate TIRE App ${{ env.version }}-mac.zip
          asset_content_type: application/zip 